import type {
  OtherSourceRow,
  ProcessingSoldProductsRow,
  UseOfSoldProductsRow,
} from "./types";

const rowId = (prefix: string) => `${prefix}-${Date.now()}-${Math.random()}`;

export const createOtherSourceRow = (): OtherSourceRow => ({
  id: rowId("other"),
});

export const createProcessingRow = (): ProcessingSoldProductsRow => ({
  id: rowId("psp"),
  processingActivity: "",
  factorType: undefined,
  combustionType: undefined,
  stationaryMainFuelType: undefined,
  stationarySubFuelType: undefined,
  stationaryCo2Factor: undefined,
  stationaryUnit: undefined,
  mobileFuelType: undefined,
  mobileKgCo2PerUnit: undefined,
  mobileUnit: undefined,
  heatSteamStandard: undefined,
  heatSteamType: undefined,
  heatSteamKgCo2e: undefined,
  heatSteamUnit: undefined,
  type: undefined,
  fuel: undefined,
  unit: undefined,
  quantity: undefined,
  factor: undefined,
  emissions: undefined,
  totalKwh: undefined,
  gridPct: undefined,
  renewablePct: undefined,
  otherPct: undefined,
  gridCountry: undefined,
  otherSources: [],
});

export const createUseRow = (): UseOfSoldProductsRow => ({
  id: rowId("usp"),
  processingActivity: "",
  energyConsumption: "",
  quantity: undefined,
  emissions: undefined,
  combustionType: undefined,
  stationaryMainFuelType: undefined,
  stationarySubFuelType: undefined,
  stationaryCo2Factor: undefined,
  stationaryUnit: undefined,
  mobileFuelType: undefined,
  mobileKgCo2PerUnit: undefined,
  mobileUnit: undefined,
  stationaryQuantity: undefined,
  mobileQuantity: undefined,
  hybridFuelType: undefined,
  hybridFuel: undefined,
  hybridFuelUnit: undefined,
  hybridFuelQuantity: undefined,
  hybridFuelFactor: undefined,
  hybridFuelEmissions: undefined,
  hybridTotalKwh: undefined,
  hybridGridPct: undefined,
  hybridRenewablePct: undefined,
  hybridOtherPct: undefined,
  hybridGridCountry: undefined,
  hybridOtherSources: [],
  electricityTotalKwh: undefined,
  electricityGridPct: undefined,
  electricityRenewablePct: undefined,
  electricityOtherPct: undefined,
  electricityGridCountry: undefined,
  electricityOtherSources: [],
  refrigerantType: undefined,
  refrigerantFactor: undefined,
  coolingRefrigerantQuantity: undefined,
  gasMachineryFuelType: undefined,
  gasMachineryFuel: undefined,
  gasMachineryUnit: undefined,
  gasMachineryQuantity: undefined,
  gasMachineryFactor: undefined,
});
