// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { USE_JWT_AUTH } from '@/api/config';

const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || "https://yhticndmpvzczquivpfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlodGljbmRtcHZ6Y3pxdWl2cGZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMjc4OTksImV4cCI6MjA2NzcwMzg5OX0.Oj6E-LQPDcEE2j20kzF9QTtNU9jgxDF9CMSyzboFt7Y";

// Service role key for admin operations (bypasses RLS)
// IMPORTANT: In production, this should be stored in environment variables
// For now, you'll need to replace this with your actual service role key
const SUPABASE_SERVICE_ROLE_KEY = import.meta.env.VITE_SUPABASE_SERVICE_ROLE_KEY || "YOUR_SERVICE_ROLE_KEY_HERE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// When JWT/AWS auth is on, do not keep refreshing old Supabase Auth sessions —
// those calls spam a host that may no longer resolve after the AWS migration.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: !USE_JWT_AUTH,
    autoRefreshToken: !USE_JWT_AUTH,
    detectSessionInUrl: !USE_JWT_AUTH,
  }
});

// Service role client for admin operations (bypasses RLS)
// This client can access all data regardless of RLS policies
export const adminSupabase = createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
  auth: {
    autoRefreshToken: false,
    persistSession: false
  }
});